; COLOR EXPLANATION
; main, sidebar, player = background
; card                  = cards, tracklist, dropdowns, input fields
; shadow                = text on button, tab active & selected row
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover

[monochrom]
text				=ffffff
subtext				=cccccc
main				=303030
sidebar				=242424
player				=242424
card				=404040
shadow				=1a1a1a
selected-row		=ffffff
button				=ffffff
button-active		=ffffff
button-disabled		=666666
tab-active			=ffffff
notification		=404040
notification-error	=aaaaaa
misc				=303030
